# References:
# https://github.com/marketplace/actions/flutter-action
# https://damienaicheh.github.io/flutter/github/actions/2021/05/06/flutter-tests-github-actions-codecov-en.html
# https://medium.com/mobile-development-group/github-actions-for-flutter-cf02923d7b5d
# https://petercoding.com/flutter/2021/07/18/using-github-actions-with-flutter/
# https://www.raywenderlich.com/19407406-continuous-delivery-for-android-using-github-actions
name: Todo App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '15.x'
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'
      - name: Restore packages
        run: flutter pub get
      - name: Check code lint rules
        run: flutter format --set-exit-if-changed .
      - name: Run static anaylysis
        run: flutter analyze .
      - name: Run Flutter code coverage workaround
        run: ./flutter-test-coverage-fix.sh
      - name: Run Unit Tests
        run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
          verbose: true
