# References:
# https://github.com/marketplace/actions/flutter-action
# https://damienaicheh.github.io/flutter/github/actions/2021/05/06/flutter-tests-github-actions-codecov-en.html
# https://medium.com/mobile-development-group/github-actions-for-flutter-cf02923d7b5d
# https://petercoding.com/flutter/2021/07/18/using-github-actions-with-flutter/
# https://www.raywenderlich.com/19407406-continuous-delivery-for-android-using-github-actions
# https://medium.com/@iqan/continuously-releasing-flutter-app-to-play-store-using-github-actions-eca2f5f6e996
# https://blog.codemagic.io/ci-cd-for-flutter-with-fastlane-codemagic/

# TODOs:
# cache dependencies for flutter/dart and ruby
# work out better way of doing versioning the app bundle (https://blog.codemagic.io/build-versioning-with-codemagic/)
# TODO split into parallel tasks, for example test for different platforms can run in parallel

name: Todos Beta Release

on:
  push:
    branches:
      - release/beta/*
#    OR?
#    tags:
#      - 'v*'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '15.x'
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'
          channel: 'stable'
      - name: Generate env file (TBA env specific)
        run: |
          echo "APPSYNC_ENDPOINT=$APPSYNC_ENDPOINT" >> .env
          echo "APPSYNC_AUTHORIZATION_TYPE=AMAZON_COGNITO_USER_POOLS" >> .env
          echo "COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID" >> .env
          echo "COGNITO_APP_CLIENT_ID=$COGNITO_APP_CLIENT_ID" >> .env
          echo "COGNITO_AUTH_FLOW_TYPE=USER_SRP_AUTH" >> .env
          echo "AWS_REGION=ap-southeast-2" >> .env
        env:
          APPSYNC_ENDPOINT: ${{ secrets.APPSYNC_ENDPOINT }}
          COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          COGNITO_APP_CLIENT_ID: ${{ secrets.COGNITO_APP_CLIENT_ID }}
      - name: Cat .env
        run: |
          pwd
          ls -al
          cat .env
      
